image: registry.gitlab.com/william.dev.env/co_bot/co-bot-spanish

stages:
    - test
    - deploy
    
test:
    stage: test
    script:
        - echo "Testing Runner "

deploy:
    stage: deploy 
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/prod-covid-bot-colombia.git
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/prod-covid-bot-colombia.git HEAD:master
        - echo "Deployed to Production Server  https://git.heroku.com/prod-covid-bot-colombia.git"
    environment:
        name: production
        url:  https://prod-covid-bot-colombia.herokuapp.com/
    only:
        - master
