image: registry.gitlab.com/william.dev.env/co_bot/co-bot-spanish

stages:
    - test
    - deploy
    
test:
    stage: test
    script:
        - echo "Testing Runner "

production:
    stage: deploy 
    script:
        - gem install dpl
        - dpl --provider=heroku --app=prod-covid-bot-colombia --api-key=$HEROKU_API_KEY
        - echo "Deployed to Production Server  https://git.heroku.com/prod-covid-bot-colombia.git"
    environment:
        name: production
        url:  https://prod-covid-bot-colombia.herokuapp.com/
    only:
        - master
